### ISSUE TITLE
[Agent] 自定义角色

### ISSUE THREAD

**Issue by rdmclin2** [lobehub/lobe-vidol-market#14]
### systemRole

魅魔

### agentId

2-qfrm

### avatar

https://r2.vidol.chat/files/2024/07/02/0cf60e3b-d523-4440-8a59-2e69d8d12eb3.webp

### cover

https://r2.vidol.chat/files/2024/07/02/1ba490c1-adbf-43c1-bb5b-97cb6d09df70.webp

### model

https://r2.vidol.chat/files/2024/07/02/488cf175-da49-4df4-980f-580c284ca251.vrm

### name

自定义角色

### description

这是一个自定义角色

**Comment by DavidLinch7** [comment]
1
